-- Auto-Promo AI Database Views
-- Admin views for analytics and user management
-- NOTE: Admin views are defined in schema/11-admin-views-rls.sql with proper security
-- This file kept for reference but admin views moved to 11-admin-views-rls.sql
-- SECURITY: Admin views should NEVER directly query auth.users table
-- Use SECURITY DEFINER functions and start from public.user_profiles instead 